### ISSUE TITLE
Komunikácia s databázou cez HTTP(S)

### ISSUE THREAD

**Issue by JohnyCarrot** [TIS2022-FMFI/transport-audit#10]
Na meetingu zo dňa 14.10.2022 sme sa dozvedeli, že medzi internou sieťou a internetom bude zlý firewall, ktorý má rád iba HTTP(S) komunikáciu. Keďže GEFCO má študácky server na ktorom bude môcť bežať (nie len) databáza, bude tam musieť bežať aj akýsi "medzi článok" ktorý  bude akceptovať http(s) požiadavky a na ich základe komunikovať s databázou.

**Comment by pavelpetrovic** [comment]
Bolo by skvele, keby to mohlo byt https, alebo inak kryptovane, aby tie data nechodili po internete ako pohladnica, ktoru si kazdy precita. Otazne je, ci na tom servri uz bezi nieco ine - lebo ak ano, tak bude treba pouzit ten webserver, ktory uz obsluhuje aj inu aplikaciu. Nemate nahodou aj na tuto otazku odpoved?

**Comment by JohnyCarrot** [comment]
Áno, máme prisľúbený "študentský server" na ktorom si (vraj) budeme môcť pustiť "čokoľvek" (ak by na danom servery, už bežal iný webserver, tak si komunikáciu pustím cez iný port). Plánujem tam nainštalovať Apache (web server), ktorý bude zabezpečovať HTTPS komunikáciu. 
Realita ukáže, ako to nakoniec bude, ale určite bude šifra. Ak by aj v najhoršom prípade nemohol byť (z akýchkoľvek príčin) webový server, FLASK umožňuje pripojiť certifikát (lets encrypt ich vydáva zdarma). Do kódu som certifikát zatiaľ nepridal, pretože to testujem lokálne a vlastne podpísané certifikáty by mohli robiť problém.

**Comment by pavelpetrovic** [comment]
Ďakujem za odpoveď. Áno, len to "pustiť na iný port" nezafunguje, keď tam majú firewall s otvoreným len HTTP(S).
Otázne tiež je, či ten server vôbec má nejaké doménové meno, obávam sa, že nie, lebo HTTPS sa k IP adrese bez doménového mena asi nebude dať spraviť.

**Comment by JohnyCarrot** [comment]
V prípade, že by z (napr Vami vyššie uvedených) príčin nebolo možné sprevádzkovať SSL, nie je problém šifrovať / dešifrovať text na úrovni aplikácie. Ak by takýto problém nastal, dorobí sa :)

**Comment by pavelpetrovic** [comment]
Super. Skúste to, prosím, vyšetriť, aby sme mohli mať v KP napísané čo najpresnejšie požiadavky. Ďakujem.

**Comment by JohnyCarrot** [comment]
Práve som dostal z IT oddelenia nasledujúce informácie:
1. Budeme mať vlastný hostname iba a iba pre náš projekt
2. Na študenskom servery beží webhosting, na ktorý dostaneme prístup (keďže nám vyhradia vlastný hostname, odpadá problematika portov)
3. Šifrovanie na aplikačnej úrovní nevyžadujú, SSL im príde dostatočné
4. Zabezpečenie cez "API-key" im príde dostatočné

Zaimplementujem(e) do katalógu :)
