### ISSUE TITLE
Návrh GUI - grafický návrh

### ISSUE THREAD

**Issue by MichaelU6** [TIS2022-FMFI/transport-audit#12]

**Comment by MichaelU6** [comment]
![Image](https://user-images.githubusercontent.com/72891693/197945454-21df3828-b229-4228-b4e7-cdb66050ff51.png)

**Comment by MichaelU6** [comment]
Screen po prihlásení


![Image](https://user-images.githubusercontent.com/72891693/197945581-e68ef8fe-879f-42c2-b9cd-fec03c94b81e.png)

**Comment by MichaelU6** [comment]
First screen



![Image](https://user-images.githubusercontent.com/72891693/197945638-e4bdc3d1-491a-4112-b4b8-19f90ced6915.png)

**Comment by JozefKolek** [comment]
Nastrel dobry
chyba mi tu informacia o pocte vozikov ktore moze uzivatel este naskenovat,
pri vzniknutej chybe tiez vraj nastat ze je nutne ju napravit alebo ju treba odstranit

**Comment by MichaelU6** [comment]
![Image](https://user-images.githubusercontent.com/72891693/199340033-6ecef55c-8cbb-4386-bb08-96b0ee8491eb.png)



![Image](https://user-images.githubusercontent.com/72891693/199340052-4a344623-8390-4261-9f82-4faf16fa1867.png)



![Image](https://user-images.githubusercontent.com/72891693/199340080-3efb5cf0-411f-419f-95cb-206485e1af54.png)



![Image](https://user-images.githubusercontent.com/72891693/199340095-4e480a8e-5418-4b15-94ff-da8f9ec7b023.png)



![Image](https://user-images.githubusercontent.com/72891693/199340128-fb055021-8d99-4f85-a89d-9043881c8294.png)



![Image](https://user-images.githubusercontent.com/72891693/199340151-1bf3560e-f5a8-469c-92c4-e93cd9844b91.png)



![Image](https://user-images.githubusercontent.com/72891693/199340169-81d19434-c6cb-4e7b-9f98-80f700514cb3.png)



![Image](https://user-images.githubusercontent.com/72891693/199340187-1b1492e6-b341-4de8-8db0-055fd9689ab6.png)

**Comment by JozefKolek** [comment]
K First cscreen chcelo by to inu farbu na to Logo moc to splyva
inac ziadne pripomienky skvela praca

**Comment by MichaelU6** [comment]
Tak keď dáme pozadie všade inou farbou? Rozmýšľaľ som ešte nad slabo šedou

**Comment by JozefKolek** [comment]
Plus navyse vyber zakaznika treba dat , a teda v pripade chyby  ci vyskoci navyse obrazovka alebo nie prediskutovat kludne to posli im nech si pozri a do piatka sa vyjadria

**Comment by JozefKolek** [comment]
na upravu databazy je lepsie mat mozno nejake klikatelne blbosti co si natukaju a maju , je to len vylepsovak

**Comment by MichaelU6** [comment]
[GUI3.pdf](https://github.com/TIS2022-FMFI/transport-audit/files/10073221/GUI3.pdf)
