### ISSUE TITLE
UML component diagram

### ISSUE THREAD

**Issue by JozefKolek** [TIS2022-FMFI/transport-audit#13]
@JohnyCarrot 
kordinuje

**Comment by JohnyCarrot** [comment]
![component-gefco](https://user-images.githubusercontent.com/107358703/203411920-661d328e-8930-4d92-b52d-0c6f3335c96a.png)

**Comment by JozefKolek** [comment]
skus opravit tu malu chybu co si mal s pripojenim a uploadni to tu

**Comment by JohnyCarrot** [comment]
![component-gefco (1)](https://user-images.githubusercontent.com/107358703/204642494-9302d428-a8a2-460b-bbe0-04dd010e8177.jpg)
