### ISSUE TITLE
Tvorba verejne dostupného testovacieho (nie len) databázového servera

### ISSUE THREAD

**Issue by JohnyCarrot** [TIS2022-FMFI/transport-audit#18]
Tvorba verejne dostupného PostgreSQL servera na účely tvorby aplikácie .

**Comment by JohnyCarrot** [comment]
host: server.nahovno.eu
port: 5432
meno: admin
heslo: Verejne_zname_heslo_47

**Comment by JohnyCarrot** [comment]
Postupne nahadzujem podla modelu - tu som skončil (nemôžem pokračovať kvôli nezrovnalostiam):
![kde_som_skoncil_nahadzujem](https://user-images.githubusercontent.com/107358703/198622013-d96a27bd-fdc5-4831-ad11-91677f62e1b0.png)

**Comment by JozefKolek** [comment]
![Image](https://user-images.githubusercontent.com/100275065/198820997-c2384913-7128-45e2-b5cb-138f4363af66.png)

Jop JLR header sme odstranili pretoze to nepotrebujeme ako samostatny vystup a mal by to byt uz v poriadku

**Comment by JohnyCarrot** [comment]
Ak bude plánik schválený všetkými autoritami, dokončím to. Bohužiaľ, v tomto prípade každá zmena predstavuje problém.

**Comment by JozefKolek** [comment]
Mozes kludne pokracovat model bol finally navrhnuty

**Comment by JohnyCarrot** [comment]
Tabuľky nahrané podľa #6 

![audit-preprav-ERD](https://user-images.githubusercontent.com/107358703/200142074-896ffe5d-9a3b-4e4e-a121-a327ed053b6b.png)

**Comment by JozefKolek** [comment]
general - automatic_export - na boolean 
Workstatement  work - bude text 
check a note mozu byt aj boolean

Chyby bo bol model updatnuty v stredu mal by byt v mojom pullrequeste ak si ho nevidel teda este
Config - miesto SPZ text je Vehicle_id
Vehicle pridaj entitu id a daj ako PK
SPZ text nebude PK
Shippment - Vehicle_id miesto SPZ_id
Miesto Record sme to nazvali Stillage
akoze ci je id dolezite tam asi netreba ani davat

**Comment by JohnyCarrot** [comment]
Work_statement:work - ponechám na číslo, je jednoduchšie pracovať s číslami a každému priradiť text.
Inak všetko zmenené podľa požiadavky
![audit-preprav-ERD](https://user-images.githubusercontent.com/107358703/200174080-83cb45fb-c05e-4419-b7ec-28a0acd916fa.png)

**Comment by JohnyCarrot** [comment]
pridaná databáza čisto pre web (audit-preprav-web):
prvotne zatiaľ takto:
![audit-preprav-web-ERD](https://user-images.githubusercontent.com/107358703/201354694-e2b0b4b4-e631-49a2-b275-19afcb0b9da7.png)

**Comment by JohnyCarrot** [comment]
* Problém na vyriešenie. Ak bude existovať v každom zariadení offline sqlite databáza a na viacerých zariadeniach sa v rovnakom čase vytvorí záznam, tak sa pri momentálnom type generovania ID (predošlé ID +1) vytvorí kolízia.

Riešenie: Generovať ID na základe náhody, teda nejaké náhodné číslo, alebo súhrn čísel a znakov

**Comment by JohnyCarrot** [comment]
Opravené, každý primary key (okrem user code) bude random UUID (napr "c2d29867-3d0b-d497-9191-18a9d8ee7830").
Každá tabuľka potrebuje mať vlastne ID, aby sa dalo kontrolovať, či sa jedná  o rovnaký záznam medzi databázami.

![ERD-audit-preprav](https://user-images.githubusercontent.com/107358703/201635300-e1955980-dc49-432c-81b4-651f6118905f.png)

**Comment by JohnyCarrot** [comment]
Do REST API pridané všetky tabuľky ako triedy (viď REST-API brench)

**Comment by JohnyCarrot** [comment]
Do databázy nahrané náhodné dáta cez GENERATE-SCRIPT
Vracanie tabuliek ako JSON vymyslené, ale zatial nie úplne hotové

**Comment by JohnyCarrot** [comment]
Keďže SQLite nepozná veľa dátových typov, bolo treba trochu zmeniť dátový model. Zmeny sa týkajú len tabuľky Stillige:
* TLS_range --> TLS_range_start a TLS_range_stop oba big int
* Note text[] --> zmenený čisto len na textový typ s tým, že bude aj tak obsahovať list (repr) a do pythonu bude nahraný cez val

![ERD-audit-preprav](https://user-images.githubusercontent.com/107358703/202182656-9d69dccf-1f48-46c0-98e7-c11d1079a3d2.png)

Zmeny by mali byť nahodené všade, kde je to potreba :)

**Comment by JohnyCarrot** [comment]
Pridaná SQLite db so základnou štruktúrou

**Comment by JohnyCarrot** [comment]
Pridaná synchronizácia server --> local
* dorobiť ešte local -> server

**Comment by JohnyCarrot** [comment]
Pridaná synchronizácia client -> server
server.py teraz skutočne beží na servery (nie lokálne), na ktorý sa dá dopytovať
upravené názvy stlpcov v tabulge "Stillage", názvy tabuliek tvorili chyby (2 hodky fuč :) )

Ešte doriešiť SSL a row data gateway a bude hotovo

Nový ERD:
![audit-preprav-ERD](https://user-images.githubusercontent.com/107358703/202872289-e0f74185-7e88-47d4-9a69-b65122db05fc.png)

**Comment by JohnyCarrot** [comment]
Nahral som zatial kostru 3 tabuliek

Ešte treba upraviť synchronizačný proces, pretože všeobecná tabuľka "General" má svoje neduhy

* treba každej tabuľke pridať "last sync" stlpec, aby sa jednoducho a hlavne nezameniteľne dala vykonávať synchonizácia a nenastala strata nových dát

**Comment by JohnyCarrot** [comment]
* Poriešená synchronizácia na použitelnú úroveň (zaoberá sa aj timestampami)
* Pridané classy, treba ale ešte dopísať testy
* Do updatu pridať handle aj error kodov, nie len nepripojenia k databáze etc
* Nový ERD:

![audit-preprav-ERD](https://user-images.githubusercontent.com/107358703/204049281-97e617d0-b40a-42b0-8062-e64eb5302afe.png)

**Comment by JohnyCarrot** [comment]
Opravené umiestnenie databázy
Zopár testov vytvorených

* Treba dorobiť ešte aby sa dali vracať obsahy nie len ako dict, ale aj ako classy

**Comment by JohnyCarrot** [comment]
Opravená a otestovaná štruktúra databázy a tried

Dorobiť testy pre kontrolu obsahu na vzdialenom servery

**Comment by JohnyCarrot** [comment]
Testy pre kontrolu obsahu spravené. Databáza ako taká vyzerá byť použiteľná :)

**Comment by JohnyCarrot** [comment]
Pridaný konfiguračný súbor (config.py) a pridané metodky

**Comment by JohnyCarrot** [comment]
![audit-preprav-ERD](https://user-images.githubusercontent.com/107358703/206862638-7c3d3443-10bc-4231-88b1-21e9a3501266.png)

Pridaná možnosť "vymazať" záznam. Viac pozri manuál

**Comment by JohnyCarrot** [comment]
12.12 som napísal Kullovi nech mi dá prístup na študentský server
