### ISSUE TITLE
decide on implementation platform

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2022-FMFI/transport-audit#2]
Your project is not very complex, it might be worth to spend some time considering options for implementing it as an app for Android as it would significantly improve the client's benefits.

Android apps can be written in Python language, check this post:
https://stackoverflow.com/questions/49955489/how-to-develop-android-app-completely-using-python

**Comment by murodrap** [comment]
rozhodli sme sa pre aplikaciu pre adroid
