### ISSUE TITLE
Rozbehanie kivy na pycharm

### ISSUE THREAD

**Issue by JozefKolek** [TIS2022-FMFI/transport-audit#25]
https://kivy.org/doc/stable/tutorials/pong.html#getting-started
Odporucam si toto vyskusat ak to pojde mate to dobre zrobene ti ktori idete na pycharm

**Comment by JozefKolek** [comment]
![image](https://user-images.githubusercontent.com/100275065/200194482-48d16cee-2033-4f3c-9ecb-fb237ed6e35c.png)
usefull na vytvorenie QR kodov plus ziskanie textu z nich

**Comment by JohnyCarrot** [comment]
Tu je kodik na fotoapku čo z toho vyzisti čiarový kod. 
[foto+barcode.zip](https://github.com/TIS2022-FMFI/transport-audit/files/9947046/foto%2Bbarcode.zip)

**Comment by JohnyCarrot** [comment]
[foto+barcode.zip](https://github.com/TIS2022-FMFI/transport-audit/files/9993325/foto%2Bbarcode.zip)

Pridal som label do ktorého sa vkladá práve prečítaný kód... Keďže chcem apku vyskúšať na mobile, žiaľ dnes ma jeden linux zradil, po zápočtoch si nahrám inú distribúciu.

**Comment by JohnyCarrot** [comment]
Podarilo sa mi (konečne) rozbehať skompilované kivy na androide. Treba ešte poriešiť zmenu fotoaparátov, na telefónoch napr s macrom by "náhoda" bola dosť problém :D 

[foto+barcode.zip](https://github.com/TIS2022-FMFI/transport-audit/files/10055383/foto%2Bbarcode.zip)

**Comment by JohnyCarrot** [comment]
Ok, aspoň na mojom androide opencv za žiadnych okolností nevedel prečítať čiarový kód. V budúcnosti prerobím čítanie, momentálny spôsob je aj tak stupidný.
