### ISSUE TITLE
Návrh všeobecne

### ISSUE THREAD

**Issue by JohnyCarrot** [TIS2022-FMFI/transport-audit#27]
Tu by sa mali písať podstatné info k návrhu, ktoré ale nepatria do konkrétnych častí návrhu.

Všetkých som Vás do dokumentov pridal a vytvoril základnú štruktúru.

Odkaz na dokument návrhu:
https://docs.google.com/document/d/1TwVA7Kv6SLxTA7jNF-3ypNCpO4xvZ9ir-ROv3Q6vfxY/edit?usp=sharing

**Comment by JozefKolek** [comment]
[Navrh.pdf](https://github.com/TIS2022-FMFI/transport-audit/files/10421262/Navrh.pdf)
Finalny navod
