### ISSUE TITLE
Tvorba katalógu požiadaviek

### ISSUE THREAD

**Issue by JohnyCarrot** [TIS2022-FMFI/transport-audit#3]
Prvá časť katalógu požiadaviek - Jozef Kolek
Druhá časť dokumentu - Michal Uhrin
Tretia časť : Funkčné požiadavky - Terézia Strišovská
Tretia časť  : Zbytok -  Roman Božik

**Comment by JozefKolek** [comment]
[Katalóg požiadaviek(version-1).pdf](https://github.com/TIS2022-FMFI/transport-audit/files/9748295/Katalog.poziadaviek.version-1.pdf)
posielame na schvalenie

**Comment by pavelpetrovic** [comment]
* v perspektive by sa mozno mohlo spomenut, ake dalsie interakcie systemu s okolim existuju (export udajov, alebo ich zobrazenie?)
* Po skončení práci ?
* skontrolujte gramaticke chyby a formulacie
* s obrazovkou?
* celkovo bude system nainstalovany iba na jednom zariadeni alebo na viacerych? bude sa admin prihlasovat z ineho zariadenia?
* Uzivatel - nenazvat to jednoznacnejsie?
* 3.1.1.2. je ďalší pracovník hocikto?
* 3.1.1.2 nerozumiem, je to trochu nejednoznacne
* autorizuje/autentifikuje?  preco nie prihlasuje
* 3.1.2.1 co su práva jednotlivých pracovníkov
* kde ta databaza je?  (nevidim to ani v perspektive)
* 3.1.2.2 prosim zistit presnejsie a potom sem zapisat
* 3.1.2.3. akym sposobom
* 3.1.3.1.1. Pre jedného zákazníka - slovo zakaznik sa tu objavilo prvy raz, nerozumiem
* 3.1.3.2.2. pridajte "pozri 3.1.4.1"
* 3.1.3.3.2. prosim pisat cele vety nie hesla
* 3.1.3.4.1. hovori o rodine, ale nebolo to nikde vysvetlene. niedkde pridat. do slovnika? zaroven by citatel chcel nieco vediet o strukture vstupnych dat z exportov, aby tomu rozumel
* 3.1.4.1. nie su to dve poziadavky?
* 3.1.4.4. vozík => vozik ktory bol chybny znovu
* 3.1.3.4.2.  - aky cas uzavretia sa vtedy pouzije?
* 3.1.3.4.3. prosim cele vety, rozsah TLS => dve 4-ciferne cisla? systémové poradie nikde nebolo vysvetlene, co to je? kedy je mozne robit ten export? ako sa export iniciuje - automaticky, alebo tlacidlom? musi sa urobit, nemusi? zdoraznit, ze v exporte je len jedno auto. co by zadavatel povedal na TXT namiesto PDF? lebo ak chcu PDF, mozno chcu aj firemne logo alebo nejaku hlavicku... je meno pracovnika v exporte? povie kam ho ulozit?
* chyba struktura kodov (8 miestne, cyklicky opakujuce sa...)
* 3.1.5.1. dvojjazycne? viacjazycne? pomenovat ktore jazyky?
* rozsirene poziadavky - su optional?
* 3.1.5.2. prosim vysvetlit
* IONO vs JONO
* 3.1.5.3. je to jednoznacne ake to ma dosledky? => treba spomenut, ze aplikacia bude pouzivat TLS vo vystupoch, ale sparuje si ich podla vstupnych dat
* 3.2.4. bude stacit kapacita media? ked ich bude uz 100000? upresnit po dohode (one drive, lokalne medium)
* 3.2.5. prepisat -> prepisat z dovodu lokalizacie alebo prisposobenia aplikacie
* 3.2.6. mi pripada skor ako funkcionalita
*

**Comment by JozefKolek** [comment]
[Katalóg požiadaviek(2-nd-version).pdf](https://github.com/TIS2022-FMFI/transport-audit/files/9814923/Katalog.poziadaviek.2-nd-version.pdf)
@pavelpetrovic posielame na kontrolu, pripomienky boli zohladnene

**Comment by pavelpetrovic** [comment]
* vzor v slovniku - z popisu v slovniku som nepochopil ako to funguje
* report - citatel netusi, ci je vstupny alebo vystupny v slovniku a v odkazoch - pridat par slov ?
* v 2.2. nie som si isty pojmom "vozidlo" - asi ide o typ vozidla
* "Po ukončení skenovania vozidla a začatí" - pridat moznost ukoncit aplikaciu a poslat posledny neposlany report
* admin a uzivatel - zmiatlo ma, ze je roznym sposobom to iste napisane
* 2.4. zariadenie v sklade - neviem co to je - pridat do slovnika? alebo vysvetlit? - celkovo 2.4. ma zmiatlo
* Zoznam pracovníkov bude uložený v externej databáze. - ktora je iba sucastou vyvijaneho systemu a bezi na pocitaci spravovanom spolocnostou zadavatele dostupnom cez internu siet/internet
* 3.1.1.1. - prosim urcit, ktore udaje z reportu system ulozi
* 3.1.1.1. - v case behu aplikacie
* 3.1.1.2. - este raz sa zamysliet, moze to sposobit zbytocne vazne zdrzanie prace pri urcitom type tech. problemov
* 2.1. - prosim upratat vsetky vstupy a vystupy a aj lokalne ukladane subory a vlastnu databazu
*  s tym suvisi 3.1.1.4. ktore ma zmiatlo
* 3.1.2.1. - kod - pridat ze, tento stringovy kod je pre ucely autentifikacie zakodovany do QR kodu
* v slovniku zakaznik, pridat nieco ako - kazde vozidlo je v datach priradene jednemu zakaznikovi
* 3.1.3.1.3. - minimalne odporucam pouzivat typ vozidla namiesto vozidlo a niekde vysvetlit, ze su k dispozicii len tie typy vozidiel, ktore su v datach o vzoroch
* 3.1.3.1.4. - nerozumiem, ci jeden vzor moze byt priradeny aj viacerym vozidlam, ak nie, tak tato poziadavka vyplyva z toho, ze niekto musi vyrobit vzory
* 3.1.4.2. novy odstavec :-)  ano, prosim specifikovat ako chybu odstranit
* chyba poziadavka (moze byt oznacena ako volitelna) - keď je otvorené vozidlo, aplikácia niekde neustále zobrazuje počet zostávajúcich vozíkov do naplnenia vzoru

**Comment by JozefKolek** [comment]
[Katalóg požiadaviek - Dokumenty Google.pdf](https://github.com/TIS2022-FMFI/transport-audit/files/9904054/Katalog.poziadaviek.-.Dokumenty.Google.pdf)
Malo by to byt komplet doplnene caka na kontrolu od vas @pavelpetrovic

**Comment by murodrap** [comment]
[KatalógPožiadaviek.pdf](https://github.com/TIS2022-FMFI/transport-audit/files/10069118/KatalogPoziadaviek.pdf)
Katalóg upravený na základe posledných pripomienok
