### ISSUE TITLE
Špecifikácia vonkajších interfejsov

### ISSUE THREAD

**Issue by JozefKolek** [TIS2022-FMFI/transport-audit#5]
budeme riesit

**Comment by JohnyCarrot** [comment]
Prvotný nástrel
[Špecifikácia vonkajších interfejsoiv.docx](https://github.com/TIS2022-FMFI/transport-audit/files/9859073/Specifikacia.vonkajsich.interfejsoiv.docx)

**Comment by JozefKolek** [comment]
Za mna ako nastrel moze byt

**Comment by JohnyCarrot** [comment]
Pridané scenáre a entity

[Specifikacia.vonkajsich.interfejsoiv.docx](https://github.com/TIS2022-FMFI/transport-audit/files/9882302/Specifikacia.vonkajsich.interfejsoiv.docx)

**Comment by JohnyCarrot** [comment]
Spomenutá synchronizácia medzi "internou" a  "vonkajšou" databázou

[Specifikacia.vonkajsich.interfejsoiv.docx](https://github.com/TIS2022-FMFI/transport-audit/files/9895355/Specifikacia.vonkajsich.interfejsoiv.docx)
