### ISSUE TITLE
Dátový model perzistentných údajov

### ISSUE THREAD

**Issue by JozefKolek** [TIS2022-FMFI/transport-audit#6]
3 fáza projektu

**Comment by JozefKolek** [comment]
Okej zaciname tvorit

**Comment by JozefKolek** [comment]
![image](https://user-images.githubusercontent.com/100275065/197256747-68c9a36b-b41c-49bf-b524-1a2e1f1227bc.png)
Takze poprosim o kontrolu ci moze takto vyzerat databaza pre patterny pouzivatelov a kamiony s spz

**Comment by murodrap** [comment]
Ešte treba doplniť, akého typu sú jednotlivé atribúty. 
V patterne asi  pri rôznych zákaníkoch budú rozdielne počty používaných typov vozíka, takže by mohlo byť vhodnejšie dať samostatnú tabuľku pattern, ktorá bude mať atribúty id a zákazník, a potom zvlášť tabuľku s jednotlivými typmi vozíkov a ich počtom, ktoré sa budú odkazovať na pattern, do ktorého patria.

**Comment by JozefKolek** [comment]
Dakujem ano dorobim plus suhlasim tie patterny bude lepsie mat samostatne aby vedel zadavatel nove typy vozikov pridat

**Comment by JozefKolek** [comment]
![image](https://user-images.githubusercontent.com/100275065/197276407-0865c6c2-0bdc-4d89-a414-6e1edaa367e0.png)
![image](https://user-images.githubusercontent.com/100275065/197276498-95e835d5-ec78-4838-90ec-37c9bb58edc7.png)
Zatial takto ostalo viacero otazok ci nahodou neoddelit zakaznika od patternu pretoze sa mi nevidi zeby pri odstraneni zakaznika musel odist aj jeho pattern, a bolo by fajn mat tabulku vozik ale z praktickeho hladiska nas to nezaujima a ani zadavtel asi nebude chciet viest si databazu vozikov

**Comment by murodrap** [comment]
Config bude asi treba doriešiť, zakaznik a uzivatel kod by mali byť podľa informácií od zadávateľa zoznamy hodnôt, primary key by tu mal byť iný atribút tabuľky, celkovo by sa ešte hodilo ujasniť, ako presne by mal config fungovať

**Comment by murodrap** [comment]
![Screenshot from 2022-10-21 22-47-41](https://user-images.githubusercontent.com/49616040/197288132-82c10f47-216f-43be-91cd-b3cd9138924b.png)

Takto nejak som to myslela s tými patternami

**Comment by JozefKolek** [comment]
![image](https://user-images.githubusercontent.com/100275065/197344256-b46d8385-79bf-4e6d-83b6-082e46f3dcf4.png)
Este ostal JLR header ale to musim kuknut ci treba tabulku alebo staci len obrazok

**Comment by murodrap** [comment]
Tabuľa record v sebe kombinuje záznamy pre audit celého kamiónu a údaje pre jednotlivé vozíky v kamióne, aby sme sa vyhli  duplicite, bolo by dobré record rozdeliť na dve tabuľky. Inak by sa zbytočne veľakrát ukladalo napríklad v ktorom vozidle je vozík, aj keď všetky vozíky jednoho auditu musia byť v tom istom vozidle.

Môže byť tabuľka shippment, bude mať atribúty id, špz, customer_id a user_code. To sú spoločné informácie, ktoré sú zhodné pre všetky vozíky obsiahnuté v audite/zásielke.

Potom tabuľka record bude mať zvyšné atribúty, týkajúce sa už konkrétneho vozíka. Shippment_id  bude foreign key do tabuľky shippment a bude odkazovať na zásielku, ktorej je tento vozík súčasťou.

**Comment by JozefKolek** [comment]
![image](https://user-images.githubusercontent.com/100275065/197349336-444ec60d-56df-461f-b528-b8c4bca67da3.png)
Upravene s tym ze ten header neviem ci si budeme konstruovat my dodatocne z udajov v databaze alebo budeme mat k dispozicii nejaky file ktory bude len ulozeny v databaze. Ratam s poslednou variantou zatial bo k tej prvej by to chcelo dodatocne dorobit mozno dalsie tabulky a entity

**Comment by JozefKolek** [comment]
[Koubeissi2014_Epilepsy_Behav.pdf](https://github.com/TIS2022-FMFI/transport-audit/files/9844851/Koubeissi2014_Epilepsy_Behav.pdf)
Este som time_close dal do shippment lebo sa to netyka udajov suvisiacimi s vozikmi  priamo
Malo by to byt skoro final poslem potom este popis k tomu

**Comment by JozefKolek** [comment]
[Datovy_model_navrh.pdf](https://github.com/TIS2022-FMFI/transport-audit/files/9847241/Datovy_model_navrh.pdf)
Posielam aj s popisom s tym ze stale ostava dost otvorenych otazok

**Comment by JozefKolek** [comment]
![image](https://user-images.githubusercontent.com/100275065/198077439-90e94e92-9a08-4f19-915f-da40a3eed39e.png)
posielam zmeny @murodrap tvoj nazor co prerobit este/dorobit este

**Comment by JohnyCarrot** [comment]
Teraz začínam nahadzovať tabuľky do databázy a napadla mi nasledujúca vec:
Napr keď nahadzujem Stillage, dáva zmysel, že jeho číslo je primary key, pretože je to jeho unikátne označenie,
Čo sa týka rozsahu, ak je môj predpoklad správny, že je to rozsah TLS - teda sekvencia, ktorá sa (po čase) môže meniť, nemalo by to byť "obyč číslo" a nie primary key ?

**Comment by JozefKolek** [comment]
![image](https://user-images.githubusercontent.com/100275065/198654075-02aa843e-b1b2-4703-94ae-48399f490caa.png)
pche zmenene a lepsie, plus pripomienky zahrnute ako gratis

**Comment by murodrap** [comment]
Z config ešte treba odstrániť atribút user_code, keďže namiesto neho teraz používame tabuľku advanced_user

**Comment by JozefKolek** [comment]
![image](https://user-images.githubusercontent.com/100275065/198820867-38e0456c-4130-483d-8379-9b4794492ba0.png)cize toto je finalny model pridam popis a mozme to poslat zadavatelovi
